# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
