# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default=b'', max_length=100)),
                ('service_id', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
