# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20160106_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
