# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 07:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(default=b'', max_length=100)),
                ('service_list', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=b''), size=None)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
