# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 09:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='service_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=b''), size=None),
        ),
    ]
