# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_no', models.EmailField(default=b'', max_length=100)),
                ('amount', models.CharField(default=b'', max_length=100)),
                ('expiry_date', models.EmailField(default=b'', max_length=100)),
            ],
        ),
    ]
