# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='credit_card_no',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
