# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0002_auto_20160217_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit_card',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='credit_card',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='credit_card',
            name='credit_card_no',
        ),
        migrations.RemoveField(
            model_name='credit_card',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='credit_card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 11, 55, 37, 331563, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
