# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 08:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message=b"Enter country code. Phone number must be entered in the format: '919999999'.", regex=b'^\\+?1?\\d{12}$')])),
                ('email', models.CharField(default=b'', max_length=100)),
                ('city', models.CharField(default=b'', max_length=100)),
                ('service', models.CharField(default=b'', max_length=100)),
                ('category', models.CharField(default=b'', max_length=100)),
                ('sub_category', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
