# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_user_data_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='password',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
