# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_user_data_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='address',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
