# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_auto_20160213_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='service',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='sub_category',
        ),
    ]
