# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 07:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_user_data_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=b''), size=None),
        ),
    ]
