# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0008_auto_20160215_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='details',
        ),
    ]
