# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 07:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0011_remove_user_data_detail_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='detail_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=b''), default={}, size=None),
            preserve_default=False,
        ),
    ]
