# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transition_id', models.CharField(default=b'', max_length=100)),
                ('service_id', models.CharField(default=b'', max_length=100)),
                ('category_id', models.CharField(default=b'', max_length=100)),
                ('sub_category_id', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
