# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_providers',
            name='service_id',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
