# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_list',
            new_name='Get_details',
        ),
    ]
