# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_transition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='required_date',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
