# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_required_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='required_date',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
