# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20160220_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='required_time',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
