# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_category', '0002_auto_20160106_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='price',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
