# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_category', '0003_sub_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
