# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_category', '0004_sub_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='payment',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
